/**
 * Navigation map, keyed by Figma node id.
 *
 * GENERATED by tools/gen_hotspots.py — the wiring decisions live in that
 * script, not here, so node ids cannot drift. Do not edit by hand.
 *
 * `source` records where each wire came from:
 *   figma     — an interaction already authored in the Figma file
 *   corrected — present in the file but pointing at the wrong screen
 *   added     — implied by the design but never wired
 */

export interface Hotspot {
  /** Destination screen name, matching Screen.name. */
  to: string
  source: 'figma' | 'corrected' | 'added'
  /** Why this differs from the file, where it does. */
  note?: string
}

export const HOTSPOTS: Record<string, Hotspot> = {
  // 01 The problem
  "145:1178": { to: "04.1 Trip creation", source: "added", note: "the International Roaming row states the problem this flow solves" },
  // 01 The problem
  "145:1276": { to: "04.1 Trip creation", source: "added", note: "the Travel tile \u2014 the prototype's front door" },
  // 04.1 Trip creation
  "41:1637": { to: "04.2 Destination and dates", source: "figma" },
  // 04.2 Destination and dates
  "41:2176": { to: "04.1 Trip creation", source: "figma" },
  // 04.2 Destination and dates
  "45:2337": { to: "04.4 Pack selection", source: "figma" },
  // 04.2 Destination and dates
  "I45:2300;41:1729": { to: "04.3 Trip details filled", source: "figma" },
  // 04.3 Trip details filled
  "45:2398": { to: "04.2 Destination and dates", source: "figma" },
  // 04.3 Trip details filled
  "45:2423": { to: "04.4 Pack selection", source: "figma" },
  // 04.4 Pack selection
  "52:2719": { to: "04.3 Trip details filled", source: "figma" },
  // 04.4 Pack selection
  "61:3375": { to: "04.6 Review and billing", source: "figma" },
  // 04.4 Pack selection
  "65:3877": { to: "04.5 Pack detail", source: "figma" },
  // 04.5 Pack detail
  "65:3679": { to: "04.6 Review and billing", source: "figma" },
  // 04.5 Pack detail
  "65:3784": { to: "04.4 Pack selection", source: "corrected", note: "04.5 back arrow pointed at 04.3; you arrive here from 04.4" },
  // 04.6 Review and billing
  "70:4028": { to: "04.4 Pack selection", source: "corrected", note: "04.6 back arrow pointed at 04.3" },
  // 04.6 Review and billing
  "76:4211": { to: "04.7 Confirmation", source: "figma" },
  // 04.7 Confirmation
  "100:646": { to: "04.5 Pack detail", source: "added" },
  // 04.7 Confirmation
  "100:686": { to: "05.1 Setup checklist", source: "figma" },
  // 04.7 Confirmation
  "82:4429": { to: "05.2 Connected confirmation", source: "added", note: "the Travel tile returns to the live trip" },
  // 05.1 Setup checklist
  "101:955": { to: "04.7 Confirmation", source: "corrected", note: "05.1 is reached from the confirmation help card" },
  // 05.10 Notification missed call charges
  "137:5405": { to: "05.4 Trip dashboard", source: "added", note: "a notification opens the screen it is about" },
  // 05.11 Notification not connected
  "113:1892": { to: "05.3 Not connected troubleshooting", source: "added", note: "a notification opens the screen it is about" },
  // 05.12 Notification live activity widget
  "114:1910": { to: "05.4 Trip dashboard", source: "added", note: "a notification opens the screen it is about" },
  // 05.12 Notification live activity widget
  "114:1931": { to: "05.4 Trip dashboard", source: "added", note: "the expanded Live Activity card opens the live trip" },
  // 05.13 Notification connected
  "107:1449": { to: "05.2 Connected confirmation", source: "added", note: "a notification opens the screen it is about" },
  // 05.2 Connected confirmation
  "113:1788": { to: "05.4 Trip dashboard", source: "added", note: "the Travel tile returns to the live trip" },
  // 05.3 Not connected troubleshooting
  "120:2633": { to: "05.4 Trip dashboard", source: "added", note: "the Travel tile returns to the live trip" },
  // 05.4 Trip dashboard
  "I132:3484;130:3262": { to: "05.5 Trip dashboard low balance", source: "figma" },
  // 05.5 Trip dashboard low balance
  "134:4075": { to: "05.4 Trip dashboard", source: "added", note: "the Travel tile returns to the live trip" },
  // 05.5 Trip dashboard low balance
  "I137:4622;132:3470": { to: "05.4 Trip dashboard", source: "figma" },
  // 05.6 Pack ended
  "137:4878": { to: "05.4 Trip dashboard", source: "added", note: "the Travel tile returns to the live trip" },
  // 05.6 Pack ended
  "I137:5193;137:5189": { to: "04.4 Pack selection", source: "added", note: "no add-days screen was designed; re-entering pack selection is the closest real path" },
  // 05.7 Notification pack ended
  "137:5597": { to: "05.6 Pack ended", source: "added", note: "a notification opens the screen it is about" },
  // 05.7 Notification pack ended
  "137:5609": { to: "05.6 Pack ended", source: "added", note: "a notification opens the screen it is about" },
  // 05.8 Notification pack ending soon
  "137:5571": { to: "05.5 Trip dashboard low balance", source: "added", note: "a notification opens the screen it is about" },
  // 05.9 Notification usage warnings
  "137:5542": { to: "05.5 Trip dashboard low balance", source: "added", note: "a notification opens the screen it is about" },
  // 05.9 Notification usage warnings
  "137:5557": { to: "05.5 Trip dashboard low balance", source: "added", note: "a notification opens the screen it is about" },
}

/** Wires present in the Figma file but deliberately not used. */
export const REMOVED: Record<string, string> = {
  "41:2271": "04.1 CTA is rendered disabled and would skip 04.2 and 04.3",
  "61:3451": "04.4 'Other Plans' is a section header, not a link",
  "61:3515": "04.5 sheet body covered the whole screen and swallowed the accordions",
}
